### ISSUE TITLE
Error retrieving tags/etiquettes from Babelio

### ISSUE THREAD

**Issue by ofostier** [lrpirlet/cal-babelio_db#2]
It seems that plugin cannot retrieve etiquettes from Babelio

**Comment by lrpirlet** [comment]
> It seems that plugin cannot retrieve etiquettes from Babelio

Maybe some development of your statement could help!!! What book, what setup, what version, what else??? 

The only fact I am able to gather is : you are in trouble while using cal-babelio_db, Personally, the last time I used it, I could get all the tags or some of the tags depending on their color and the setting of babelio_db.

Please have a look in this [babelio_db topic on mobileread](https://www.mobileread.com/forums/showthread.php?t=349713), then set the log to maximum output before retrying a book in babelio.com that show some tags (yes, not all books have tags)

Note: I follow both GitHub and mobileread.com via email notification. Most people use mobileread.com to report trouble, so if you open a new entry over there, many people will learn something from your bad experience.

;-)

**Comment by ofostier** [comment]
Sorry,
The error was between the chair and the computer ....
I'm probably blocked by babelio :/
Everything works fine behind a VPN.

I find something maybe useful to retrieve the correct cover size.
Cover size are automatically generated by the URL.
In https://m.media-amazon.com/images/I/4146ASlxtrL._SX210_.jpg the
SX210 value initiate cover size
when replacing SX210 by SX450 you increase the cover size

I close this issue
Merci pour ton retour

**Comment by lrpirlet** [comment]
That is not an error, this is protectionism from babelio.com... 

They sincerely believe that they protect the site by banning those who use it a creative way...
